apiVersion: v1
kind: Service
metadata:
  name: heli-server-svc
spec:
  type: NodePort
  selector:
    app: heli-server
  ports:
   - nodePort: 30163
     protocol: TCP 
     port: 5000
     targetPort: 5000

# kubectl apply -f s-nodeport.yaml