apiVersion: v1
kind: Service
metadata:
  name: heli-server-svc
spec:
  selector:
    app: heli-server
  ports:
   - protocol: TCP 
     port: 5000
     targetPort: 5000
  
  


  # kubectl apply -f s-service.yaml